### ISSUE TITLE
Sugerencia para futura compatibilidad / Suggestions for future compatibility

### ISSUE THREAD

**Issue by magonra** [theripper93/animated-walls#5]
Sugerencia para futura compatibilidad:

La consola de Foundry VTT avisa de incompatibilidad para futuras versiones por hacer uso del elemento #data en lugar de #document
En mi ordenador, he modificado los archivos script/walls.js y script/WallAnimations.js
Cambiando la cadena ".data." por ".document." en ambos archivos, todo funciona correctamente y la consola no avisa de ningún problema.

---------

Suggestions for future compatibility:

The Foundry VTT console warns of incompatibility for future versions by using the #data element instead of #document.
On my computer, I have modified the script/walls.js and script/WallAnimations.js files.
Changing the string ".data." for ".document." in both files, everything works correctly and the console does not warn of any problem.

**Comment by theripper93** [comment]
The module is no longer supported
